[package]
authors = ["dyk <359743984@qq.com>"]
edition = "2018"
name = "random_str"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rand = "0.8.3"
